version: '2.1'
services:
  sa-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      AUTH_URL: '172.17.0.1'
      AUTH_PORT: '4000'
      AUTH_USERS_ENTRY: 'sa-auth-ms/resources/users'
      SERVICES_URL: '172.17.0.1'
      SERVICES_PORT: '4005'
      SERVICES_COMPANYS_ENTRY: 'api/company'
      MAPS_URL: '35.224.135.194'
      MAPS_PORT: '4003'
      MAPS_USERS_ENTRY: 'coordinate'
    ports:
      - '5000:5000'
