version: '2.1'
services:
  sa-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      AUTH_GSERVICES_URL: '172.17.0.1'
      AUTH_GSERVICES_PORT: '4000'
      AUTH_GSERVICES_ENTRY: ''
    ports:
      - '5000:5000'
