version: '2.1'
services:
  sa-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      AUTH_URL: '172.17.0.1'
      AUTH_PORT: '4002'
      AUTH_USERS_ENTRY: 'ridesupport-profileconfig-ms/resources/cars'
    ports:
      - '5000:5000'
