version: '2.1'
services:
  sa-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      AUTH_URL: '172.17.0.1'
      AUTH_PORT: '3000'
      AUTH_USERS_ENTRY: ''
    ports:
      - '5000:5000'
